### ISSUE TITLE
Cocoapods Fails To Initialize on Xcode 12.5 Image

### ISSUE THREAD

**Issue by mccarron** [CircleCI-Public/macos-big-sur-preview-docs#5]
On the new Xcode 12.5 image when trying to run `bundle exec pod install --repo-update` fails every time, this works fine right now on the pre-Big Sur images.

> Updating local specs repositories
> Adding spec repo `trunk` with CDN `https://cdn.cocoapods.org/`
> [!] Unable to add a source with url `https://cdn.cocoapods.org/` named `trunk`.
> You can try adding it manually in `/Users/distiller/.cocoapods/repos` or via `pod repo add`.

Even reverting the [CDN changes you have documented](https://circleci.com/docs/2.0/testing-ios/#optimizing-cocoapods) doesn't seem to work. 

> Cloning spec repo `cocoapods` from `https://github.com/CocoaPods/Specs.git`
> [!] Unable to add a source with url `https://github.com/CocoaPods/Specs.git` named `cocoapods`.
> You can try adding it manually in `/Users/distiller/.cocoapods/repos` or via `pod repo add`.

Any help would be great.

**Comment by TNicholson11** [comment]
Came to post the same thing... started testing with the Big Sur 12.5 image and getting 
```
[!] Unable to add a source with url `https://cdn.cocoapods.org/` named `trunk`.
```

Also tried 
```
source `https://github.com/CocoaPods/Specs.git`
```

Also tried running
```
pushd ios && pod repo add-cdn trunk https://cdn.cocoapods.org/ && pod install && popd
```
and got
```
$ pushd ios && pod repo add-cdn trunk https://cdn.cocoapods.org/ && pod install && popd
~/*******************/ios ~/*******************
Adding spec repo `trunk` with CDN `https://cdn.cocoapods.org/`
[!] Could not create '/Users/distiller/.cocoapods/repos', the CocoaPods repo cache directory.
Errno::EEXIST: File exists @ dir_s_mkdir - /Users/distiller/.cocoapods
```

Everything works fine for us on 12.4.0. Perhaps the new machines have a different network configuration?

**Comment by jbelkins** [comment]
Having the same issue on this, with the same error message.  Please fix & advise.

**Comment by BytesGuy** [comment]
Hi folks, thanks for reporting this. We are still looking into why this issue is being introduced specifically in the 12.5 image, bug as a temporary workaround please add the following command _before_ running any `pod` commands:

```
- run: rm ~/.cocoapods 
```

This should unblock you until we find the root cause of the issue.

Thanks!

**Comment by jbelkins** [comment]
@BytesGuy Your `rm ~/.cocoapods` fix clears this problem, thanks.
Please let us know when you've fixed it on the VM so we can pull this step from our build scripts.

**Comment by TNicholson11** [comment]
> Hi folks, thanks for reporting this. We are still looking into why this issue is being introduced specifically in the 12.5 image, bug as a temporary workaround please add the following command _before_ running any `pod` commands:
> 
> ```
> - run: rm ~/.cocoapods 
> ```
> 
> This should unblock you until we find the root cause of the issue.
> 
> Thanks!

Can also confirm the workaround works... deleting that ~/.cocoapods directory doesn't allow us to cache pods so we're very much looking forward to a permanent solution to this issue before moving into our production flow(s).

That being said, our iOS build time was reduced by ~50% on the new hardware. Very excited about the improvements.

**Comment by wdy-gogolook** [comment]
Hi folks. Here is my workaround and I hope this could help.

It seems that `pod install` stores repositories to `~/.cocoapods/repo`. CircleCI's Xcode 12 container has the file `~/.cocoapods` and that would stop cocoapods from making the directory `~/.cocoapods/repo`. 

Meanwhile, I read [Cocoapods' document](https://guides.cocoapods.org/using/faq.html#can-i-change-the-default-cocoapods-repositories-folder) and I set the environment variable CP_HOME_DIR to another path (mine is `~/.cocoapods-home`)

For the cache-saving issue, My config.yml uses this:
```
      - save_cache:
          key: `<my cache key>`
          paths:
            - $CP_HOME_DIR
            - `<other cache paths>`
```

I haven't verify whether this saves cache properly yet. I'll check this later.

**Comment by lriverawong** [comment]
Hello everyone.
Thank you for your patience, a new version of the image has been deployed with no changes necessary to your CI config for `12.5.0`. This new version fixes the `cocoapods` directory issue.
```
ls -la ~/.cocoapods/
total 8
drwxr-xr-x   3 distiller  staff    96 May 21 04:32 .
drwxr-xr-x+ 35 distiller  staff  1120 May 21 14:47 ..
-rw-r--r--   1 distiller  staff    14 May 21 04:32 config.yaml
```
This updated image replaces the old `12.5.0` image and therefore does not require any changes to your CI config. 
Please reach out if you have any other issues.
