### ISSUE TITLE
WWDR intermediate certificate fails to install on Big Sur VMs

### ISSUE THREAD

**Issue by jbelkins** [CircleCI-Public/macos-big-sur-preview-docs#6]
Tried installing Apple's latest WWDR intermediate certificate on the Big Sur VM's keychain using the steps outlined here:

https://support.circleci.com/hc/en-us/articles/360052459251-Resolving-Enterprise-iOS-Code-Signing-Failures-due-to-WWDR-Intermediate-Certificate-Expiration

When this step is reached, it sits and does not complete.  No further actions or build steps are performed.

Both the `110.12.4` and `12.5.0` VMs hang on this step.

**Comment by alexazl** [comment]
We are aware of this issue and are working on a fix. I will be sure to let you know once I have an update!

**Comment by lriverawong** [comment]
Hello @jbelkins 
I just wanted to let you know that all all images have this WWDR certificate already in place. In addition to this it was also added onto the `12.5.0` image. The manual additions will always hang / fail due to a change in `macOS 11` that forces a GUI based password entry which was not present in `macOS 10.15`. 
If you have any other questions, feel free to reach out.

**Comment by alexazl** [comment]
> Tried installing Apple's latest WWDR intermediate certificate on the Big Sur VM's keychain using the steps outlined here:
> 
> https://support.circleci.com/hc/en-us/articles/360052459251-Resolving-Enterprise-iOS-Code-Signing-Failures-due-to-WWDR-Intermediate-Certificate-Expiration


Just to reiterate what @lriverawong mentioned, the steps outlined in the support article are no longer needed. Please remove those steps from your jobs.

**Comment by jbelkins** [comment]
@alexazl @lriverawong I just removed the steps cited above and attempted to code sign on CircleCI again.  
Here is the VM I used:
```
    macos:
      xcode: 12.5.0
      resource_class: m2.medium
```

My build failed on code-signing.  This is the error message I received, same as when the needed WWDR intermediate certificate is not installed:
```
[17:13:44]: ▸     /usr/bin/codesign --force --sign 8743C2D6334C2C5C2568EE4CEF02FB7D7D23B110 /Users/distiller/Library/Developer/Xcode/DerivedData/Trala-fcelgdlrekepqfdriwlqbwvflojw/Build/Intermediates.noindex/ArchiveIntermediates/Trala/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/TralaPackages.framework
[17:13:44]: ▸ Warning: unable to build chain to self-signed root for signer "Apple Development: Created via API (942YD76D7Q)"
[17:13:44]: ▸ /Users/distiller/Library/Developer/Xcode/DerivedData/Trala-fcelgdlrekepqfdriwlqbwvflojw/Build/Intermediates.noindex/ArchiveIntermediates/Trala/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/TralaPackages.framework: errSecInternalComponent
[17:13:44]: ▸ Command CodeSign failed with a nonzero exit code
```
This indicates that my signing certificate is present but the WWDR intermediate is not.  And please bear in mind, this Fastlane script and these signing certificates are working everyday with your stable VMs.  Please advise on what to try next.

**Comment by junpluse** [comment]
Same here.

In my case, it seems to be happening when the CocoaPods script signs frameworks during archiving the app.

```
PhaseScriptExecution [CP]\ Embed\ Pods\ Frameworks /Users/distiller/project/Build/DerivedData/Build/Intermediates.noindex/ArchiveIntermediates/__APP_NAME__/IntermediateBuildFilesPath/__APP_NAME__.build/Debug-iphoneos/__APP_NAME__.build/Script-6A7AE14B1DE3B53268F96593.sh (in target '__APP_NAME__' from project '__APP_NAME__')
    cd /Users/distiller/project
    /bin/sh -c /Users/distiller/project/Build/DerivedData/Build/Intermediates.noindex/ArchiveIntermediates/__APP_NAME__/IntermediateBuildFilesPath/__APP_NAME__.build/Debug-iphoneos/__APP_NAME__.build/Script-6A7AE14B1DE3B53268F96593.sh
mkdir -p /Users/distiller/project/Build/DerivedData/Build/Intermediates.noindex/ArchiveIntermediates/__APP_NAME__/BuildProductsPath/Debug-iphoneos/__APP_NAME__.app/Frameworks
Symlinked...
rsync --delete -av --filter P .*.?????? --links --filter "- CVS/" --filter "- .svn/" --filter "- .git/" --filter "- .hg/" --filter "- Headers" --filter "- PrivateHeaders" --filter "- Modules" "/Users/distiller/project/Build/DerivedData/Build/Intermediates.noindex/ArchiveIntermediates/__APP_NAME__/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/AppAuth.framework" "/Users/distiller/project/Build/DerivedData/Build/Intermediates.noindex/ArchiveIntermediates/__APP_NAME__/InstallationBuildProductsLocation/Applications/__APP_NAME__.app/Frameworks"
building file list ... done
AppAuth.framework/
AppAuth.framework/AppAuth
AppAuth.framework/Info.plist

sent 1407279 bytes  received 70 bytes  2814698.00 bytes/sec
total size is 1406873  speedup is 1.00
Code Signing /Users/distiller/project/Build/DerivedData/Build/Intermediates.noindex/ArchiveIntermediates/__APP_NAME__/InstallationBuildProductsLocation/Applications/__APP_NAME__.app/Frameworks/AppAuth.framework with Identity Apple Development: Created via API (__TEAM_ID__)
/usr/bin/codesign --force --sign __IDENTITY__  --preserve-metadata=identifier,entitlements '/Users/distiller/project/Build/DerivedData/Build/Intermediates.noindex/ArchiveIntermediates/__APP_NAME__/InstallationBuildProductsLocation/Applications/__APP_NAME__.app/Frameworks/AppAuth.framework'
Warning: unable to build chain to self-signed root for signer "Apple Development: Created via API (__TEAM_ID__)"
/Users/distiller/project/Build/DerivedData/Build/Intermediates.noindex/ArchiveIntermediates/__APP_NAME__/InstallationBuildProductsLocation/Applications/__APP_NAME__.app/Frameworks/AppAuth.framework: errSecInternalComponent
Command PhaseScriptExecution failed with a nonzero exit code
```

It was working fine until a few days ago.

I suspect that [the most recent update](https://github.com/CircleCI-Public/macos-big-sur-preview-docs/issues/5#issuecomment-846141556) to the `xcode: 12.5.0` image may be the cause.

**Comment by lriverawong** [comment]
Hello
Could you both please ensure that your locally generated certificates reference the new WWDR certificate? 
You can do so by verifying that `Organizational Unit = G3`.
We have just verified the existence of both certificates within the image.

Also are you using [`setup_circle_ci`](https://docs.fastlane.tools/actions/setup_circle_ci/)?

**Comment by junpluse** [comment]
@lriverawong 

> Your locally generated certificates reference the new WWDR certificate?

Yes. `Organization Unit` is `G3`.

> Also are you using [`setup_circle_ci`](https://docs.fastlane.tools/actions/setup_circle_ci/)?

Yes.

**Comment by elitalon** [comment]
@lriverawong Same error here. Our builds were working fine on Xcode 12.5.0 prior to the [recent outage](https://mobile.twitter.com/CircleCIstatus/status/1395911931295244290).

We are also using `setup_circle_ci` and the `Organization Unit` is `G3`.

**Comment by lriverawong** [comment]
Thank you for all for your patience.
We are currently working on the patch to get this fixed. I will provide you all with an update as soon as possible.

**Comment by lriverawong** [comment]
An image update has been deployed with the certificate fix. 
Please retry your builds and let us know if you have any more problems relating this this.
Thank you for your patience!

**Comment by jbelkins** [comment]
@lriverawong I just rebuilt.  Code signing succeeded for me 🎉

**Comment by bpollman** [comment]
Working great for us as well.

**Comment by junpluse** [comment]
Works fine for us too! Thanks 👍

**Comment by elitalon** [comment]
@lriverawong Working again on our side, thanks!
