### ISSUE TITLE
Unexpected error preparing a VM for this build

### ISSUE THREAD

**Issue by skarol** [CircleCI-Public/macos-big-sur-preview-docs#8]
Cannot get VM assignment today. 
```
Build-agent version 1.0.65096-7c79c780 (2021-05-26T16:44:13+0000)
Creating a dedicated VM with xcode:12.5.0 image
Waiting for a VM assignment: ...........................................................................................................................................................................................................................
We had an unexpected error preparing a VM for this build, potentially due to our infrastructure or cloud provider.  Please retry the build in a few minutes
```

**Comment by IUFlo** [comment]
same for me :-(

**Comment by TanNguyenEH** [comment]
I got same issue, :((

**Comment by ttkien** [comment]
I am facing this error too

**Comment by Wavemaster111188** [comment]
Same for me 😢

**Comment by lriverawong** [comment]
Hello,
Can you confirm if you are using `m2.medium` or our older `medium` resource class?

**Comment by IUFlo** [comment]
Yes in our case we are using m2.medium.

**Comment by alexazl** [comment]
Thank you all for your patience! We believe we have just resolved the issue that was resulting in VM assignment errors. Please retry your builds and let us know if you continue to run into the problem.

**Comment by lriverawong** [comment]
If possible, please let us know if this has resolved the errors you are experiencing, thank you.

**Comment by TanNguyenEH** [comment]
Thank you very muchhhh, for me, it's working now, :))

**Comment by IUFlo** [comment]
it is working now, thank you. 👍

**Comment by skarol** [comment]
Works for me as well. I'm using `m2.medium`. Thanks for the quick fix.
